### ISSUE TITLE
Refatorar tema atual e implementar infraestrutura de temas

### ISSUE THREAD

**Issue by caiosba** [ejplatform/ej-front#2]
- [x] Extrair as cores do tema atual e salvá-las como variáveis no SASS
- [x] Implementar uma infraestrutura de temas em que cada tema é um subdiretório dentro de um diretório `themes` na raiz, que contém pelo menos um arquivo SASS que redefine as variáveis de cores definidas no tema padrão (mas que pode conter outros arquivos SASS com outras regras de estilo)
- [x] Definir e implementar o mecanismo de alteração de tema (que pode ser em tempo de compilação ou execução, a ser decidido)
- [x] Implementar uma infraestrutura de hotspots que permita que um tema sobrescreva componentes específicos, e implementar um hotspot para rodapé e um exemplo de tema que o implemente
- [x] Permitir alterar o tema em runtime

**Comment by ricardopoppi** [comment]
puxando o @laurybueno pra dar uma olhada nessa proposta pra ja ir refletindo nesse merge pro bpq mais pra frente

**Comment by laurybueno** [comment]
Um problema dessa abordagem é o que o @brunosmartin comentou no grupo do Telegram. Vou tentar destrinchar melhor o argumento aqui.

Quando os arquivos de diversos temas ficam dentro do repositório principal, não estamos fazendo uma solução realmente modularizada. Digo isso porque, nesse sistema, terceiros que queiram subir instâncias de EJ com temas próprios vão, necessariamente, forkar este repositório e criar suas próprias pastas de temas. Apesar de essa abordagem ser possível, ela nos priva de possibilidades de escalabilidade.

O cenário ideal, na nossa opinião aqui no hacklab, é que cada tema seja um pacote npm independente e cada instalação filha instala o tema que quiser (sem precisar ter uma versão dela do ej-front). Uma coisa interessante que surge com essa proposta é a existência de vários pacotes de temas no npm que podem ser usados facilmente por outras pessoas (mesmo as que não fizeram nenhum dos temas).

Claro que isso traz a questão: dá pra fazer um tema ser um pacote npm?

**Comment by caiosba** [comment]
Eu gostei da ideia do pacote NPM, vou experimentar.

**Comment by leandronunes** [comment]
Eu acho que a proposta de agora é o caminho para ser criar no futuro um pacote npm.
Então eu acho que entrega mais valor começarmos essa generalização dos estilos e criação de variáveis para permitir a criação mais fácil de temas e depois investirmos na criação de um pacote npm separado.
No que diz respeito a criação do pacote npm a única diferença que vejo é que na pasta themes teríamos links simbólicos para pastas existentes no node_modules. Mas no que diz respeito a utilização do tema ficaria igual ao que temos hoje.
E a ideia não é que os arquivos dos novos temas fique no controle de versão deste projeto não. Está agora somente para definirmos qual será a proposta e facilitar a implementação desta proposta. Depois de pronto podemos extrair estes temas do repositório para locais mais apropriados (pacote npm poderia ser uma alternativa)

A priori alguém poderia até mesmo criar um tema (que seria somente um diretório na pasta themes) e compartilhar esta pasta do tema com qualquer outra pessoa e para usá-los bastaria extrair a pasta dentro da pasta themes de modo parecido com o wordpress.

**Comment by fabiommendes** [comment]
Acho a abordagem do Leandro correta enquanto a gente prepara uma estrutura melhor para integrar pacotes do NPM ou pastas de tema que o usuário simplesmente copia para algum lugar. Andei atrás de soluções no Sass, mas aparentemente não tem nada pronto ainda. O plano dos devs do Sass para imports dinâmicos vai ajudar bastante no futuro:

- Refatorar os imports internamente e usar o comando @use ao invés de @import (evita conflito  com uma sintaxe CSS válida e aparentemente o sistema de import deles não está muito bom)
- Criar uma função load() que consegue carregar um arquivo .scss dinamicamente a partir de um nome de variável.

Quando tivermos a função load(), a implementação do tema ficará bem mais fácil (mesmo para temas externos) sem a necessidade de muita gambiarra no package.json. Minha sugestão é seguir com a abordagem do Leandro e esperar a função load() aparecer no Sass.

**Comment by laurybueno** [comment]
Verdade, pessoal. Acho justo entendermos a abordagem de agora como uma porta de entrada para uma solução melhor que teremos no futuro.

Bora por esse caminho então

**Comment by caiosba** [comment]
Concluí a implementação de uma estrutura de hotspots nos temas, o que permite que a aplicação defina partes dela que podem ser sobrescritas por temas. Por enquanto implementei um primeiro hotspot, para validar a estrutura, que permite que temas tenham um rodapé próprio. Utilizei o `theme-blue` como exemplo de tema que implementa um rodapé próprio. O código está no commit https://github.com/ejplatform/ej-front/pull/3/commits/fcfb9e7136bbe8154c07026791fdb8988051ddcd no branch `theme-infrasctructure`.

**Comment by caiosba** [comment]
Pessoal, eu acho que a versão atual já pode ir para `develop`, o que acham?

**Comment by fabiommendes** [comment]
Esta estrutura permite redefinir temas em runtime? Confesso que prefiro a abordagem de modificar algumas variáveis Sass + Links simbólicos. Pra mim ficou muito complexo e parece trabalhoso criar cada tema. Dá mais flexibilidade, mas a gente não precisa desta flexibilidade toda agora.

**Comment by caiosba** [comment]
> Confesso que prefiro a abordagem de modificar algumas variáveis Sass + Links simbólicos.

A solução ainda faz isso, Fábio... só que, além disso, permite que o tema implemente alguns componentes específicos... pelo menos o rodapé (que é o que já foi implementado), é muito comum ser específico por tema. Mas não é obrigatório... um tema pode definir apenas as variáveis do SASS.

> Esta estrutura permite redefinir temas em runtime?

Sim, mas ainda não tem interface pra isso.

**Comment by fabiommendes** [comment]
Oi Caio,

Só pra ver se entendi: o hostpost de tema consegue dar override completo em alguns componentes (não só aplicar CSS). É isso? 

É bom pensarmos quais componentes fazem sentido ter override. Pra mim são estes em ordem de prioridade
* Footer (mudar estrutura, links, logos, info, etc)
* Talvez partes do header/logo (mas talvez só a background image seja o suficiente) 
* Login?
* A landing page poderia ser personalizável, mas acho que cada projeto deveria se responsabilizar por isso individualmente

O resto acho que se resolve com CSS. 

Ainda não sei em que ponto a gente faz a divisão e diz que mudar o componente precisa de um fork.  Como o footer tem um use-case muito claro, podemos seguir este caminho. Se for o único componente que precisa de personalização (fora CSS), talvez até valha a pena estudar uma gambiarra com <div (innerHTML)=footerData>
e salvar um possível HTML + CSS do footer como uma model no backend.

A parte de mudar o tema em runtime não é necessária então seguimos sem ;)

**Comment by caiosba** [comment]
> Só pra ver se entendi: o hostpost de tema consegue dar override completo em alguns componentes 
> (não só aplicar CSS). É isso?

Isso! Já implementei a infraestrutura que permite que componentes contenham hotspots que permitam customização por parte de temas.

> É bom pensarmos quais componentes fazem sentido ter override

Concordo!

> Footer (mudar estrutura, links, logos, info, etc)

Já implementei para o footer e implementei um exemplo de tema que customiza o footer, para fins de exemplo e didática.

Com relação aos demais pontos, eu acho que depende dos casos de uso de cada tema. Por enquanto o único caso que imaginei foi o do footer e header (logo, slogan, etc.) e talvez o menu lateral (para incluir alguns links externos talvez).

**Comment by fabiommendes** [comment]
Algumas coisas podem ter comportamento dinâmico. Creio que o caso dos links adicionais, por exemplo, poderia ter um endpoint  para alimentar este conteúdo já que o mesmo poderia mudar durante a vida do projeto. Temos que ver com o UX que partes seriam extensíveis desse modo.

Quanto ao header, diria que pra trocar só o logo é melhor usar CSS. Mas realmente pode ser interessante fazer outras mudanças estruturais em outros casos.
