### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#21]
Componente conversations do [wireframe](https://projects.invisionapp.com/d/main#/console/13881288/290122038/build)

**Comment by caiosba** [comment]
Feito. Implementei um estilo básico para o tema Brasil Que o Povo Quer e para o tema padrão, conforme screenshots em anexo.

Tema padrão:

![21-default](https://user-images.githubusercontent.com/117518/38711571-dfabad34-3e9c-11e8-8097-3293c262d52e.png)

Brasil Que o Povo Quer:

![21-bpq](https://user-images.githubusercontent.com/117518/38711572-dfd9b01c-3e9c-11e8-8c03-5998bae06181.png)

**Comment by caiosba** [comment]
@leandronunes por favor revisar.
