### ISSUE TITLE
Ajustar o responsivo do Top Header

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#24]

**Comment by leandronunes** [comment]
É preciso realizar os ajustes necessários para a versão mobile

**Comment by luizapeixe** [comment]
oi @leandronunes , minha sugestão é que o top header entre dentro do menu hamburguer mesmo, com uma hierarquia de apresentação menor do que os demais links, tipo assim:
![dropdown_mobile](https://user-images.githubusercontent.com/6249788/38709279-88aeadc6-3e90-11e8-8205-2ae5364223ea.png)

**Comment by Heloisecs** [comment]
Quanto ao menu superior, concordo que os itens devam ir para o hamburger.

Quanto à solução proposta, para mim é um problema de usabilidade, descrito no documento de análise de usabilidade do Brasil que o povo quer:
3
Problema:(!)
Para acessar os itens principais de menu, na interface mobile, usuário deve clicar no símbolo “menu hambúrguer” e depois clicar em “Conversas”, “Perfil”, “Comentários” - Destinos que deveriam estar mais acessíveis - um clique. 

Soluções(…)
(1)Menu Principal, com pelo menos as opções “Conversas” (que é o centro do aplicativo), “Perfil” (importante o acesso por conta da gamificação), “Comentários” (já que o comentário do usuário não é publicado imediatamente na conversa, esta seção é importante para que o usuário saiba qual o status do comentário).

**Comment by Heloisecs** [comment]
Também comentei que "Ver perfil" seria mais importante que fazer log out, continuo com a proposta de que esse mesmo seria melhor se acessado por um clique e o log out ir para o menu hamburguer, pensando no mobile first.

**Comment by luizapeixe** [comment]
essa versão de header realmente não está atualizada com as ultimas soluções pros WFs.. usei a imagem mais para exemplificar o dropdown

Sobre os conteúdos, houve uma orientação de destacar os itens "conheça o CPA"; "grupos de debate"; "conversas" e "perfil" na [versão desktop](https://projects.invisionapp.com/d/main#/console/13881288/290122038/preview). Entretanto na [versão mobile](https://projects.invisionapp.com/d/main#/console/13881288/289718293/preview) mais aprovada até o momento estamos destacando (por ícones) os itens "conversas"; "acesso ao rocket" e "perfil". Por isso comentei na [issue 25](https://github.com/ejplatform/ej-front/issues/25) que não tenho certeza se já temos uma definição oficial dos conteúdos do header nesse momento. Alguém está melhor informado sobre essas definições?

**Comment by leandronunes** [comment]
vou colocar esta issue como pendente até ser fechado o design

**Comment by ricardopoppi** [comment]
issue deprecada com a entrega e os novos wireframes. fechando...
