### ISSUE TITLE
Ajusta o responsivo do header

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#25]
É preciso definir como o conteúdo do Header ficará na versão mobile.
 - Os links 'conheça o CPA', 'grupos de debate' e 'conversas' vão para o "hamburger" ou sumirão?
- os links do perfil serão relocados para o header na versão mobile?

**Comment by luizapeixe** [comment]
não sei se já temos a nomenclatura real oficial dos itens do header neste momento... temos, @parrahenri ?

**Comment by leandronunes** [comment]
vou colocar esta issue como pendente até ser fechado o design

**Comment by parrahenri** [comment]
Nada real oficial antes da aprovação pela cliente mesmo (não rolou ainda), mas vamos com esse conteúdo que está indicado e tentaremos manter na conversa com elas…

O fato é que a cliente ainda não respondeu agendando essa reunião, então estamos decidindo avançar e tocar pra frente e depois minimizar os riscos de mudança.

**Comment by ricardopoppi** [comment]
issue deprecada com a entrega. fechando...
