### ISSUE TITLE
Conteúdo do Header para usuários deslogados

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#27]
Quando um usuários estiver deslogado deve mostrar os botões 'Entrar' e 'Registra-se'?
Ao clicar neste botões aparecerá uma modal?

**Comment by luizapeixe** [comment]
minha sugestão seria que o usuário deslogado pudesse acessar todas as páginas, porém sem interação com as conversas ou outras areas exclusivas para usuários cadastrados. Deste modo o conteúdo do header poderia se manter igual porém, no lugar de "Perfil", teria o item "Entrar" com as opções em dropdown: "Login" e "Cadastre-se". O que vcs acham?

**Comment by Heloisecs** [comment]
Concordo, Luiza, só colocaria o login não como uma opção de menu, num exemplo bem rascunhado:

<img width="300" alt="screen shot 2018-04-12 at 21 00 41" src="https://user-images.githubusercontent.com/9471715/38710071-b62f1502-3e94-11e8-9c55-eed07d498451.png">

**Comment by luizapeixe** [comment]
se não me engano, em algum momento foi comentado que a página de login deveria ser uma página independente (confesso q não entendi completamente o porquê...), como é a do gmail, por exemplo. Essa info confere, galere dos códigos?

**Comment by Heloisecs** [comment]
Entendi, me lembro do @fabiommendes falando algo nesse sentido mesmo, como está essa decisão?

**Comment by leandronunes** [comment]
vou colocar esta issue como pendente até ser fechado com funcionará essa questão.

**Comment by ricardopoppi** [comment]
issue deprecada com o novo front. fechando...
