### ISSUE TITLE
Criar conteúdo para o link Sobre

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#28]
É preciso definir o conteúdo de https://dev.ejplatform.org/sobre-nos

**Comment by parrahenri** [comment]
Criado aqui: https://docs.google.com/document/d/1qeDHazJn_tSv9N9H6kEjDW4pBVbYcDXGz2wtKP4ZmMY/edit?usp=sharing

@luizapeixe veja! @ricardopoppi em cópia
