### ISSUE TITLE
Criar conteúdo para o link Perguntas frequentes

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#29]
https://dev.ejplatform.org/perguntas-frequentes

**Comment by parrahenri** [comment]
Criado aqui: https://docs.google.com/document/d/1qeDHazJn_tSv9N9H6kEjDW4pBVbYcDXGz2wtKP4ZmMY/edit?usp=sharing

@luizapeixe veja! @ricardopoppi em cópia
