### ISSUE TITLE
Criar conteúdo para o link Termos de uso

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#30]
É preciso definir o conteúdo de https://dev.ejplatform.org/termos-de-uso

**Comment by parrahenri** [comment]
Criado aqui: https://docs.google.com/document/d/1qeDHazJn_tSv9N9H6kEjDW4pBVbYcDXGz2wtKP4ZmMY/edit?usp=sharing

@luizapeixe veja! @ricardopoppi em cópia
