### ISSUE TITLE
Ajustes no card de conversas

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#35]
- [x] Centralizar horizontalmente e verticalmente a descrição da conversa.

- [x] Colocar o assunto centralizado na base do topo do card

- [x] colocar os comentários abaixo do topo do card

- [x] colocar os votos abaixo do topo do card

**Comment by leandronunes** [comment]
combinamos de realizar este ajuste depois de finalizada a proposta do layout

**Comment by caiosba** [comment]
Bom, implementei com base no layout atual (https://projects.invisionapp.com/d/main#/projects/boards/6029080/179822258). Em anexo, um screenshot que mostra a implementação da tela de conversas com base na versão atual do tema padrão.
![35](https://user-images.githubusercontent.com/117518/38824782-c412eb96-4180-11e8-805a-578185447d5a.png)
