### ISSUE TITLE
Complementar Rodapé

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#36]
Adicionar as informações 'Venha somar....' no componente do rodapé.

De acordo com:

https://projects.invisionapp.com/share/PKGOLD0N25F#/screens/290122038

**Comment by lucashm** [comment]
@leandronunes Essa parte faz parte do footer mesmo? Acho melhor criar outra área pra compor esse pedaço, já que ela não se repete em todas as páginas, somente na home. O que você acha?

**Comment by leandronunes** [comment]
achei que fosse se repetir. 
Se não for é melhor criar outro componente sim e chamar ele no HomeComponent

**Comment by lucashm** [comment]
Beleza! Vou trabalhar nisso pra entregar amanhã!

**Comment by ricardopoppi** [comment]
issue deprecada. fechando..
