### ISSUE TITLE
Ajustar Componente que exibe uma conversa

### ISSUE THREAD

**Issue by leandronunes** [ejplatform/ej-front#38]

**Comment by leandronunes** [comment]
A nova exibição da conversa será de acordo com o definido em:

https://projects.invisionapp.com/d/main#/console/13881288/289718289/build

**Comment by leandronunes** [comment]
O atual componente de conversa já atende as definições do wireframe

**Comment by ricardopoppi** [comment]
issue deprecada, fechando
