### ISSUE TITLE
Estudo de proposta de arquitetura do CSS

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#46]
A nova proposta de arquitetura de css segue a arquitetura ITCSS
e a metodologia BEM.

### ITCSS

É a arquitetura de triângulo invertido do CSS para ajudar a organizar
os arquivos e expecificadores CSS. Ele apresenta 7 camadas de organização.
As primeiras camadas são mais genéricas e a especificidade aumenta,
coforme desce nas camadas.

- Settings: configurações globais, por exemplo, cores, fontes, definições.
- Tools: compreende funções e mixins.
- Generic: estilizações genéricas que impactam toda a aplicação.
Por exemplo, resets, regras de box-sizing.
- Elements: elementos do HTML sem classe. Por exemplo, h1, a.
- Objects: elementos com seletoes de classe. Exemplo, wrappers e containers.
- Components: partes reconhecíveis da UI, de fato. Novos componentes, ficam aqui.
- Utilities: utilities e classes helper, que sobrescrevem outras. (cuidado: !important)
- Temas: sobrescreve as varíaveis e outras configurações.

### BEM

É uma metodologia de organização e criação de classes CSS.
BEM significa: Block Elements Modifiers.
Isso traduz como ele propõe a criação de classe.

- Block: tem significado próprio. Pedaços da UI.
- Elements: é parte de um bloco, e está semanticamente atrelado a ele.
- Modifiers: uma flag no bloco ou no elemento e modifica a aparência padrão.

### Suit

É uma convenção para nomear classes CSS e definir melhor o escopo dos componentes.
A sintaxe de nomeação é a seguinte 
`[<namespace>-]<ComponentName>[-descendentName][--modifierName]`.
Por exemplo, o componente de banner na página inicial tem a classe `HomeBanner`.
Uma seção no banner da página inicial seria `HomeBanner-section`.
Uma seção de destaque, por exemplo, `HomeBanner-section--large`.

**Comment by BrunaNayara** [comment]
Essa estrutura já pode ser [observada no back](https://github.com/ejplatform/ej-server/tree/develop/lib/scss). Estou terminando um exemplo no front. Mas se formos atacar as prioridades seguindo a proposta da [issue 28](https://github.com/ejplatform/ej-server/issues/28), irei juntar meus esforços segundo a decisão e finalizo o exemplo  no front depois do dia 30.

**Comment by ricardopoppi** [comment]
Decisão tomada. Os componentes do front serão prioritariamente react. Fechando essa issue, mas ela fica como referencia para a arquitetura do front.
