### ISSUE TITLE
Componente de votação com Polymer 

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#47]
Criar o componente de votação de conversa utilizando Polymer. Levar em consideração os seguintes aspectos para serem discutidos: 
- Comunidade
- Die gracefully (mesmo com erros, é possível utilizar a aplicação)
- comunicação com outros frameworks (a integração foi fácil? Quais as dificuldades?)
- comunicação com a arquitetura de css
- Testes

**Comment by ricardopoppi** [comment]
Deixaremos esse teste para outro momento. Decisão tomada. Os componentes do front serão prioritariamente react.
