### ISSUE TITLE
Componente de votação com React

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#48]
Criar o componente de votação de conversa utilizando React. Levar em consideração os seguintes aspectos para serem discutidos: 
- Comunidade
- Die gracefully (mesmo com erros, é possível utilizar a aplicação)
- comunicação com outros frameworks (a integração foi fácil? Quais as dificuldades?)
- comunicação com a arquitetura de css
- Testes

**Comment by caiosba** [comment]
Eu implementei a lista de conversas e a votação de uma conversa utilizando React. Funcionou muito bem. O código está em https://github.com/ejplatform/ej-server/compare/experiment/48-react.

Funcionalidades:

- Sessão de usuário
- Layout
- Responsividade / mobile first
- Lista de conversas
- Página de conversa específica
- Votação

Vídeo mostrando o funcionamento: https://www.youtube.com/watch?v=whg4eULausE

Observações:

- Não implementei tradução, mas é possível com react-intl
- A configuração é feita através de um arquivo config.js, onde atualmente tem o host do backend
- A ideia do CSS é ser único por componente, por isso SCSS não é muito útil mas é mais útil para variáveis (tamanhos e cores)
- A ideia é ter componentes bem auto-contidos, por exemplo, um título pode ser um componente Title que é apenas um h1 estilizado
- Isso é bacana porque facilita os testes unitários
- A ideia é reutilizar componentes, não seletores de CSS
- Mas pode ser diferente também, é possível reutilizar seletores de CSS
- Não implementei login porque pode continuar no backend seguindo nossa ideia de ser mais seguro assim
- Mudanças foram necessárias na API, para expor o token de usuário no endpoint /me
- A API sumiu? Exceto user, os demais endpoints só encontro em arquivos de cache do Python
- Integração com FontAwesome
- A ação de votar não pôde ser concluída porque a API no backend não está funcionando
