### ISSUE TITLE
Componente de votação com Stencil

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#49]
Criar o componente de votação de conversa utilizando Stencil. Levar em consideração os seguintes aspectos para serem discutidos: 
- Comunidade
- Die gracefully (mesmo com erros, é possível utilizar a aplicação)
- comunicação com outros frameworks (a integração foi fácil? Quais as dificuldades?)
- comunicação com a arquitetura de css
- Testes

**Comment by leandronunes** [comment]
https://github.com/ejplatform/ej-server/pull/59

**Comment by leandronunes** [comment]
Segue o PR com o código para rodar o stencil.
A pasta /ej/templates/stencil/conversation é o app stencil.
Minha percepção subjetiva sobre a comunidade é que teremos bastante dificuldade para fazermos coisas mais complexas na aplicação. Ao mesmo tempo não sei se teremos muitas coisas complexas nestas componentes previstos para este projeto.

**Comment by leandronunes** [comment]
Criei esete packge npm https://www.npmjs.com/package/ej-conversation

**Comment by leandronunes** [comment]
Exemplo de código html para usar o componente

```
<html>
  <head>
    <title>Pagina de Teste</title>
    <script type="text/javascript" src='https://unpkg.com/ej-conversation@0.0.9/dist/ejconversation.js'></script>
  </head>
  <body>
    <h1>Testando Incluir Componente</h1>
    <ej-conversation></ej-conversation>

  </body>
</html>
```

**Comment by ricardopoppi** [comment]
Decisão tomada. Os componentes do front serão prioritariamente react.
