### ISSUE TITLE
Mover a página de login para fora do SPA

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-front#5]
É considerada uma boa prática de segurança pois impede um eventual ataque de XSS de recuperar a senha do usuário em texto plano. Essa é estratégia utilizada em vários sites grandes como gmail/twitter/facebook/dropbox, etc.

Minha proposta é remover o componente de login da página principal e criar uma página separada somente com o componente de login trabalhando na lógica de redirect.

**Comment by ricardopoppi** [comment]
Na discussão desse assunto durante a reunião foram elencadas outras abordagens, inclusive a do "reload". Eu sugiro que a abordagem escolhida leve em consideração os ajustes de usabilidade do app, pois uma nova página com redirect pode prejudicar a ux desejada, principalmente se o login deixar de ser obrigatório e passar a ser disparado por interações dentro do app.

Melhor esperar os novos wireframes pra compatibilizar a solução dessa issue de segurança com as necessidades de ux

**Comment by caiosba** [comment]
Concordo com Poppi que devemos esperar os wireframes. Mas eu acho que no pior caso pelo menos o `reload` deve ser implementado (e acredito que seja mais que suficiente como solução de segurança). Em grandes aplicações, a página de login também é separada por questões de performance... por ser igual para todos os usuários, geralmente ela é estática em cache, o que para estes sites com tráfego intenso faz muita diferença, mas no nosso caso não acho tão relevante.

**Comment by ricardopoppi** [comment]
Issue deprecada com o novo front. Fechando...
