### ISSUE TITLE
Componente de votação com VueJS

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#50]
Criar o componente de votação de conversa utilizando VueJS. Levar em consideração os seguintes aspectos para serem discutidos: 
- Comunidade
- Die gracefully (mesmo com erros, é possível utilizar a aplicação)
- comunicação com outros frameworks (a integração foi fácil? Quais as dificuldades?)
- comunicação com a arquitetura de css
- Testes

**Comment by ricardopoppi** [comment]
Deixaremos esse teste para outro momento, já tomamos a decisão da tech do front com base em react e stencil
