### ISSUE TITLE
Estratégia de integração de Web Componentes na aplicação

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-front#6]
Abri esta issue pra discutir como podemos integrar componentes no EJ. Acho que a estratégia geral pode ser assim:

* Priorizar a implementação de componentes "dumb" que se comportem basicamente como views com o mínimo de comportamento dinâmico possível.
* Em Angular, um componente pai (normalmente o responsável por cada página), seria responsável pelo controler + model e serviços do Angular.

Coisas que os componentes explicitamente NÃO devem fazer:
* Requisições à API
* Manipular o estado da aplicação
* Controlar o comportamente de outros componentes (a não ser os filhos)
* Abrir toasts e notificações
* Controlar sessões

**Comment by lucashm** [comment]
Estou pesquisando a viabilidade do Polymer.
Gostei bastante do Stencil, mas a ferramenta ainda está em fase de desenvolvimento, e uma build nova sai a cada 3 dias... Vou fazer um relatório de ambos pra nós escolhermos a melhor ferramenta.

**Comment by lucashm** [comment]
Segue a pesquisa relacionada ao uso de Web components:
Fui atrás de 3 alternativas: Polymer, Stencil e web components a partir de JS vanilla/html.

## Polymer
- Grande comunidade
- Vários componentes já existentes
- Momento de transição (Polymer 2.x para Polymer 3.0)
- Curva de aprendizado mediana
- Tamanho da aplicação consideravelmente grande (168 kb). [Polymer 2.x vs Angular 2](https://medium.com/@realabhijeet4u/angular-2-0-vs-polymer-f45a4f539238)

## Stencil
- Biblioteca/compilador recente
- Fase alpha, mas recebe constantes atualizações
- Curva de aprendizado pequena
- Tamanho da aplicação mínimo (6 kb) [Stenciljs](https://stenciljs.com/)

## Web components vanilla
- Sem uso de bibliotecas externas
- Desenvolvimento estável
- Curva de aprendizado alta
- Sem biblioteca, sem bundle

Dada a atual situação/direcionamento do projeto, creio que utilizar o Stencil seja a melhor solução, visto que a criação de componentes no mesmo é bastante acelerada, e apesar de ainda estar em fase alpha, as constantes atualizações e o carinho dos desenvolvedores pelo projeto o tornam um candido promissor.
Vale ressaltar que também consegui fazer a integração do Stenciljs com o Angular. Algumas interações ainda não funcionam bem, mas para componentes dumb/pouca interação como botões e componentes estáticos, foi possível conseguir ótimos resultados.

**Comment by ricardopoppi** [comment]
A decisão sobre os componentes do front foi tomada, usaremos react. Fechando essa issue então, mas ela fica como referencia e histórico
