### ISSUE TITLE
Remover o login forçado

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#7]
- [x] Remover login forçado
- [ ] Login não interfere no layout
- [x] Atualização de segurança
- [x] Utilizar Cookies

Remover a necessidade de login para navegar pela plataforma. O login continua sendo requerido para participar das conversas. 

Atualmente, a autenticação, ou não, reflete no layout da página (algumas funcionalidades não são apresentadas). O Layout deve ser o mesmo independente da autenticação

Observar a discussão da Issue [Mover a página de login para fora do SPA ](https://github.com/ejplatform/ej-front/issues/5) sobre estratégias de seguranca de login

O login utiliza o Local Storage ao invés de cookies (débito do polis).

**Comment by caiosba** [comment]
Estou trabalhando nisso no branch `7-login`.

**Comment by leandronunes** [comment]
https://github.com/ejplatform/ej-front/pull/13

**Comment by BrunaNayara** [comment]
O layout não-logado está diferente do layout logado. Deveria ser o mesmo

**Comment by ricardopoppi** [comment]
issue deprecada com o novo front. fechando...
