### ISSUE TITLE
Melhorar tour da plataforma

### ISSUE THREAD

**Issue by BrunaNayara** [ejplatform/ej-front#8]
Atualmente, o tour apresenta recortes da aplicação para explicar a utilização da plataforma. Esses recortes não mostram, da fato, onde realizá-los na plataforma. O tour está com passos hardcoded e é dividido em componentes que são acoplados no código. 
Estudar possibilidades de arquitetura (e/ou frameworks) de tour para flexibilizar a utilização em outros contextos.

**Comment by BrunaNayara** [comment]
@ricardopoppi e @fabiommendes se puderem complementar...

**Comment by ricardopoppi** [comment]
De acordo. Além de melhorar a arquitetura do tour já padronizaria o tour pra ser tour mesmo, ou seja, indicar no app onde estão os elementos e não trazer os elementos no modal. No momento que isso foi formulado para a FPA atendia uma demanda deles, mas a prática mostrou que não foi a melhor abordagem. Sempre lembrando, como eu falei no caso do login, que a necessidade e como será o tour virá do time de design e ux

**Comment by ricardopoppi** [comment]
issue deprecada, trabalharemos o tour já no contexto dos novos wireframes. fechando...
